[2024-08-31T00:54:28.438+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:54:28.492+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [queued]>
[2024-08-31T00:54:28.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [queued]>
[2024-08-31T00:54:28.515+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:54:28.545+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-15 00:00:00+00:00
[2024-08-31T00:54:28.561+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:54:28.564+0000] {standard_task_runner.py:64} INFO - Started process 515 to run task
[2024-08-31T00:54:28.564+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-15T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpy3bna1as']
[2024-08-31T00:54:28.571+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask extract_data
[2024-08-31T00:54:28.668+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:54:28.869+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-15T00:00:00+00:00'
[2024-08-31T00:54:28.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:54:28.876+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:54:28.877+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:54:28.901+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-15T00:00:00+00:00, execution_date=20230415T000000, start_date=20240831T005428, end_date=20240831T005428
[2024-08-31T00:54:28.931+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task extract_data (No module named 'src'; 515)
[2024-08-31T00:54:28.982+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:54:29.030+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T00:54:29.034+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:50:36.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:50:36.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [queued]>
[2024-08-31T01:50:36.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [queued]>
[2024-08-31T01:50:36.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:50:36.178+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-15 00:00:00+00:00
[2024-08-31T01:50:36.192+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:50:36.195+0000] {standard_task_runner.py:64} INFO - Started process 379 to run task
[2024-08-31T01:50:36.197+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-15T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpmr_fvy6y']
[2024-08-31T01:50:36.200+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask extract_data
[2024-08-31T01:50:36.265+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-15T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:50:36.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-15T00:00:00+00:00'
[2024-08-31T01:50:36.427+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:50:36.430+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:50:36.431+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:50:36.455+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-15T00:00:00+00:00, execution_date=20230415T000000, start_date=20240831T015036, end_date=20240831T015036
[2024-08-31T01:50:36.481+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task extract_data (No module named 'src'; 379)
[2024-08-31T01:50:36.531+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:50:36.566+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:50:36.570+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
