[2024-08-31T00:59:45.788+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:59:45.838+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-08-31T00:59:45.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-08-31T00:59:45.859+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:59:45.892+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-01 00:00:00+00:00
[2024-08-31T00:59:45.908+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=762) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:59:45.911+0000] {standard_task_runner.py:64} INFO - Started process 787 to run task
[2024-08-31T00:59:45.912+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpbsbw0uq_']
[2024-08-31T00:59:45.917+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask extract_data
[2024-08-31T00:59:46.009+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:59:46.199+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-01T00:00:00+00:00'
[2024-08-31T00:59:46.202+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:59:46.206+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:59:46.207+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:59:46.230+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-05-01T00:00:00+00:00, execution_date=20230501T000000, start_date=20240831T005945, end_date=20240831T005946
[2024-08-31T00:59:46.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task extract_data (No module named 'src'; 787)
[2024-08-31T00:59:46.288+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:59:46.343+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T00:59:46.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:55:57.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:55:57.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-08-31T01:55:57.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-08-31T01:55:57.718+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:55:57.752+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-01 00:00:00+00:00
[2024-08-31T01:55:57.769+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=673) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:55:57.772+0000] {standard_task_runner.py:64} INFO - Started process 697 to run task
[2024-08-31T01:55:57.773+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmp9p348op9']
[2024-08-31T01:55:57.778+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask extract_data
[2024-08-31T01:55:57.885+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-05-01T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:55:58.110+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-01T00:00:00+00:00'
[2024-08-31T01:55:58.114+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:55:58.117+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:55:58.118+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:55:58.143+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-05-01T00:00:00+00:00, execution_date=20230501T000000, start_date=20240831T015557, end_date=20240831T015558
[2024-08-31T01:55:58.171+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task extract_data (No module named 'src'; 697)
[2024-08-31T01:55:58.230+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:55:58.282+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:55:58.286+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
