[2024-08-31T00:54:26.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:54:26.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T00:54:26.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T00:54:26.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:54:27.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-11 00:00:00+00:00
[2024-08-31T00:54:27.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmp08w3cnk7']
[2024-08-31T00:54:27.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=467) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:54:27.076+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask extract_data
[2024-08-31T00:54:27.076+0000] {standard_task_runner.py:64} INFO - Started process 506 to run task
[2024-08-31T00:54:27.200+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:54:27.429+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-11T00:00:00+00:00'
[2024-08-31T00:54:27.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:54:27.438+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:54:27.439+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:54:27.468+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-11T00:00:00+00:00, execution_date=20230411T000000, start_date=20240831T005426, end_date=20240831T005427
[2024-08-31T00:54:27.507+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task extract_data (No module named 'src'; 506)
[2024-08-31T00:54:27.574+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:54:27.660+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T00:54:27.665+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:50:34.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:50:35.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T01:50:35.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T01:50:35.042+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:50:35.250+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-11 00:00:00+00:00
[2024-08-31T01:50:35.262+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=346) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:50:35.265+0000] {standard_task_runner.py:64} INFO - Started process 369 to run task
[2024-08-31T01:50:35.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpzobb78az']
[2024-08-31T01:50:35.271+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask extract_data
[2024-08-31T01:50:35.359+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:50:35.521+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-11T00:00:00+00:00'
[2024-08-31T01:50:35.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:50:35.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:50:35.529+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:50:35.545+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-11T00:00:00+00:00, execution_date=20230411T000000, start_date=20240831T015035, end_date=20240831T015035
[2024-08-31T01:50:35.565+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task extract_data (No module named 'src'; 369)
[2024-08-31T01:50:35.602+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:50:35.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
